### ISSUE TITLE
Add support for electric bikes

### ISSUE THREAD

**Issue by Kuitsi** [jaamo/strava2kilometrikisa#22]
Sync should have an option to log only half of the kilometers

> Jarmo Kaataja (28.04.2017 11:23) https://www.kilometrikisa.fi/contests/kilometrikisa-2017/comments/
>
> sähköavusteinen + strava ei vissiin onnistu tuota http://strava2kilometrikisa.com/? käyttäen kovin kätevästi koska kilometrit tulee sieltä 1:1 eikä 1:2 niinkuin pitäisi? 
>
> tai sitten ehkä pitää nettisivulta muokata kilometrit puoleen myöhemmin?

**Comment by jaamo** [comment]
Thanks for your feedback! That's actually something we have been thinking about. We cannot get this information from Strava API directly, but there are a few potential ways to do this:

1. Add an checkbox option to strava2kilometrikisa to enable "e-bike mode". That would be easy to do but this could be difficult if you are using both normal and electric bikes.
2. We can get bike id from Strava and we could add an option to calculate kilometers based on bike id. If we decide to implement this I would go this way.

Let's keep this on our backlog :)

**Comment by Kuitsi** [comment]
The second option sounds good. I can't help with testing, though. I'm just a captain of a team trying to get wishes from our team to you guys. I don't have Strava account nor I have electric bike. :)

**Comment by ZeroOne3010** [comment]
Note that this year there's a separate method for logging the e-bike kilometers. They are no longer logged as half the amount, contrary to the original issue description.

**Comment by vertti** [comment]
Currently this should be trivial to implement. `ActivityType` can have `EBikeRide` as type (https://developers.strava.com/docs/reference/#api-models-ActivityType). And the `ActivityType` is returned in the array of activities with `getLoggedInAthleteActivities`.

**Comment by Mattti0** [comment]
Someone who uses strava2kilometrikisa with e-bike could probably verify if [latest changes](https://github.com/jaamo/strava2kilometrikisa/pull/48) works to automatically sync e-bike kilometers? After verification this can be closed.
