### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by hugovk** [jaamo/strava2kilometrikisa#24]
I'm getting a "504 Gateway Time-out" when visiting http://strava2kilometrikisa.com.

![image](https://user-images.githubusercontent.com/1324225/34763271-3245c4e6-f5f3-11e7-872d-72cf703d4a0a.png)

A couple of days earlier it was showing a welcome page, but when clicking the login button it was giving an error (perhaps a 502?).

I don't have anything updating from Stava to Kilometrikisa this time. It was working last summer.

By the way, thanks for this tool, it's been really useful!

**Comment by dancek** [comment]
While the server is down, here's a CLI https://github.com/dancek/strava2kilometrikisa/blob/cli/node/app/cli.js . Works for me but I don't think it's good/easy enough to warrant a pull request.

**Comment by hugovk** [comment]
Thanks!

I've followed the instructions, but get this (macOS High Sierra, node 9.4.0):
```bash
$ node cli.js
/Users/hugo/github/strava2kilometrikisa/node/app/cli-secrets.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

Any tips?

**Comment by dancek** [comment]
@hugovk oh, sorry about that. I tried to use ES modules but had some issues so I switched back to CJS. Except for the template file 🤦‍♂️ . Pull again, it works now -- or change `export default { ... }` to `module.exports = { ... }`.

**Comment by dancek** [comment]
Also note that I changed the sync timeframe to be the last 30 days (it used to be last 5 days, but I had activities in early January and probably most other users do too).

**Comment by hugovk** [comment]
Great, that works now, thanks!

Except my activities are nearly all private... Would it be difficult to plumb in the Strava auth to the CLI?

**Comment by dancek** [comment]
In short, yes, it would be difficult. The tokens are static though, so you just need to get a token with the `view_private` scope once, plug it in, and it will work. See if the instructions at http://yizeng.me/2017/01/11/get-a-strava-api-access-token-with-write-permission/ are helpful.

**Comment by hugovk** [comment]
Bingo, thank you very much!

**Comment by jaamo** [comment]
FYI: service is now up and running :)

**Comment by hugovk** [comment]
Haha, perfect timing :) Thank you!

**Comment by hugovk** [comment]
Re-opening. 

https://strava2kilometrikisa.com/ is giving 504s again and kilometrikisa hasn't updated in 4 days. 

The last entry was on Friday.

**Comment by hugovk** [comment]
Working again now, thanks!
