### ISSUE TITLE
Expired certificate at strava2kilometrikisa.com

### ISSUE THREAD

**Issue by kimmoahokas** [jaamo/strava2kilometrikisa#35]
## Expected behavior

When browsing to https://strava2kilometrikisa.com/ it should open.

## Current behavior

Expired TLS certificate error is displayed and connection is blocked.

## Steps to reproduce

Go to https://strava2kilometrikisa.com/ with any browser.

## Environment

Firefox on MacOS.

## Possible solution

If you would like, I could help with backend deployment setup and automation. Let me know if there is something I could do for you :)

**Comment by hugovk** [comment]
Right now it's:

> 504 Gateway Time-out
> nginx/1.11.6

**Comment by jaamo** [comment]
We are in the middle of migrating this to Heroku :)
