### ISSUE TITLE
Autosync has stopped working entirely. Manual Sync removed? No functionality?

### ISSUE THREAD

**Issue by pythonInRelay** [jaamo/strava2kilometrikisa#45]
## Expected behavior
KMs should sync automatically @4am as stated in the FAQ
(Could we maybe also get this changed to like 11:30pm, so we can sync that day's biking on that actual same day)

## Current behavior
Does not sync automatically  ̶h̶e̶l̶l̶o̶a̶n̶d̶ ̶h̶t̶t̶p̶s̶:̶/̶/̶w̶w̶w̶.̶s̶t̶r̶a̶v̶a̶2̶k̶i̶l̶o̶m̶e̶t̶r̶i̶k̶i̶s̶a̶.̶c̶o̶m̶/̶m̶a̶n̶u̶a̶l̶s̶y̶n̶c̶ ̶p̶a̶g̶e̶ ̶i̶s̶ ̶g̶o̶n̶e̶ seems that it was now moved to https://www.strava2kilometrikisa.com/account > Manual Sync

## Steps to reproduce

1. Bike some distance
2. Have that recorded to Strava
3. KMs are not automatically syned to Kilometriskisa

## Environment
Strava Android, Web Portal

## Possible solution
Fix the autosync issue? Is it a DB issue (KMs are being sent to old kis/database?) or has maybe Kilometriskisa changed their API?

**Comment by Mattti0** [comment]
Manual sync at least seems to work, verified also that kilometers appears also to Kilometrikisa.fi
![image](https://user-images.githubusercontent.com/6770071/116855771-9e427680-ac02-11eb-97d7-ce16b1ea001a.png)

How I synced:
1. Go to https://www.strava2kilometrikisa.com
2. Log in with Strava account
3. Log in with Kilometrikisa account
4. Open "Sync manually"
5. Sync

**Comment by hannupekka** [comment]
I talked with one of the developers and there were issues with the app having an old ID for Kilometrikisa. This got fixed yesterday around 9:30 and after that manual sync worked for me. Have not had chance to test autosync yet.

**Comment by hugovk** [comment]
Thank you!

I can confirm manual sync is working, but autosync is still not working.

**Comment by pythonInRelay** [comment]
I just tested it just then with what I have biked today already. Manual sync is definitely working, automatic sync is not though. Would be really nice to get automatic sync working, as it's probably something really basic.

Thanks to everyone who has tested and looked into this so far! :)

**Comment by Mattti0** [comment]
Now also autosync is working! 🎉
