### ISSUE TITLE
#45 Autosync has stopped working again

### ISSUE THREAD

**Issue by pythonInRelay** [jaamo/strava2kilometrikisa#54]
Looks like a repeat of #45 

Has it stopped working again? I gave it a few days but it looks like I need to still do everything manually.

**Comment by hugovk** [comment]
Autosync is still working for me, it's synced all mine from last week.

**Comment by Mattti0** [comment]
Still working also for me

**Comment by onefastsnail** [comment]
Closing this as it may have been the wrong event ID configured.
