### ISSUE TITLE
Sync for 2022 talvikilometrikisa is not working

### ISSUE THREAD

**Issue by forsellj** [jaamo/strava2kilometrikisa#60]
## Expected behavior
Kilometers and time will be synced from Strava to TalviKilometrikisa 2022

## Current behavior
Not syncing even the application seems to do the sync and finds all the trainings from Strava

## Steps to reproduce
1. Have training in Strava
2. Run sync
3. Check the results from Kilometrikisa
1.

**Comment by Mattti0** [comment]
~~Best guess at the moment is that contest id need to be updated in env variables.~~

~~Contest id for winter 2022 is 46.~~

edit. That contest id seems to be fixed and works now at least for me

**Comment by forsellj** [comment]
Manual sync works now, but automatic not? What is the automatic sync schedule, is it still at night?

**Comment by hugovk** [comment]
> Manual sync works now, but automatic not? 

Automatic sync still not working for me. I just went through the authorisation stuff, let's check again tomorrow.

> What is the automatic sync schedule, is it still at night?

Yes, it's meant to be at 4 am: https://www.strava2kilometrikisa.com/faq

**Comment by hugovk** [comment]
> Automatic sync still not working for me. I just went through the authorisation stuff, let's check again tomorrow.

Now it worked 👍

**Comment by forsellj** [comment]
Yes, I can agree. Thanks!
